FROM python:3.8


RUN mkdir -p /usr/src/api
COPY . /usr/src/api

WORKDIR /usr/src/api
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn

EXPOSE 5000
ENV FLASK_APP main.py
CMD [ "flask", "run", "--host=0.0.0.0" ]