FROM node:13.1.0-alpine

ARG environment

RUN apk add --no-cache git
RUN mkdir -p /usr/src/web
#RUN yarn build

WORKDIR /usr/src/web

COPY . /usr/src/web

EXPOSE 3000
EXPOSE 35729

RUN yarn install
CMD ["yarn", "start"]